services:
  - type: web
    name: subtrakt-api
    runtime: node
    plan: free
    region: singapore
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node app.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.0.0
